platform :ios, '6.0'
xcodeproj 'github'

pod 'MMDrawerController', '~> 0.5.7'
pod 'LruCache'

pod 'Fletch', :path => '../../..'
pod 'Service', :path => '../generated/service'
pod 'Immi', :path => '../generated/immi'
pod 'ImmiSamples', :path => '../../../pkg/immi_samples/lib'
