platform :ios, '6.0'
xcodeproj 'github'

pod 'MMDrawerController', '~> 0.5.7'
pod 'LruCache'

pod 'Fletch', :path => '../../..'
pod 'Service', :path => '../packages/service'
pod 'Immi', :path => '../packages/immi'
pod 'ImmiSamples', :path => '../packages/immi_samples'
