#!/bin/sh
# Copyright (c) 2015, the Dartino project authors. Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE.md file.

### BEGIN INIT INFO
# Provides:       dartino-configuration
# Required-Start: hostname mountall $syslog
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:  S
# Default-Stop:
# Description:    Modify configuration based on files in the boot partition
### END INIT INFO

PATH=/sbin:/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

CONFIGURATION_DIR=/boot/dartino-configuration
DARTINO_HOSTNAME_CONF="$CONFIGURATION_DIR/hostname"
HOSTNAME_CONF="/etc/hostname"
DARTINO_HOSTS_CONF="$CONFIGURATION_DIR/hosts"
HOSTS_CONF="/etc/hosts"

do_start () {
  # Copy from source to dest if source exists.
  log_action_msg "Running dartino configuration manager"
  if [ -f $DARTINO_HOSTNAME_CONF ]; then
    log_action_begin_msg "Updating $HOSTNAME_CONF"

    cp $DARTINO_HOSTNAME_CONF $HOSTNAME_CONF
    chown root:root $HOSTNAME_CONF
    chmod 644 $HOSTNAME_CONF

    HOSTNAME="$(cat /etc/hostname)"
    hostname "$HOSTNAME"
    ES=$?
    log_action_end_msg $ES

    rm $DARTINO_HOSTNAME_CONF
  fi

  if [ -f $DARTINO_HOSTS_CONF ]; then
    log_action_begin_msg "Updating $HOSTS_CONF"

    cp $DARTINO_HOSTS_CONF $HOSTS_CONF
    chown root:root $HOSTS_CONF
    chmod 644 $HOSTS_CONF

    ES=$?
    log_action_end_msg $ES

    rm $DARTINO_HOSTS_CONF
  fi
  log_action_msg "Done dartino configuration manager"
}

do_status () {
  # Currently status is always OK.
  return 0;
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    do_status
    exit $?
    ;;
  *)
    echo "Usage: dartino-configuration [start|stop]" >&2
    exit 3
    ;;
esac
