// Copyright (c) 2015, the Fletch project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE.md file.

service PersonCounter {
  Int32 GetAge(Person person);
  Int32 GetBoxedAge(PersonBox box);
  AgeStats GetAgeStats(Person person);
  AgeStats CreateAgeStats(Int32 averageAge, Int32 sum);
  Person CreatePerson(Int32 children);
  Int32 Count(Person person);
}

struct AgeStats {
  Int32 averageAge;
  Int32 sum;
}

struct Person {
  Int32 age;
  List<Person> children;
}

struct PersonBox {
  Person person;
}
