// Copyright (c) 2015, the Fletch project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE.md file.

service PersonCounter {
  int32 GetAge(Person person);
  int32 GetBoxedAge(PersonBox box);
  AgeStats GetAgeStats(Person person);
  AgeStats CreateAgeStats(int32 averageAge, int32 sum);
  Person CreatePerson(int32 children);
  Node CreateNode(int32 depth);
  int32 Count(Person person);

  int32 Depth(Node node);
}

struct AgeStats {
  int32 averageAge;
  int32 sum;
}

struct Person {
  int32 age;
  List<Person> children;
}

struct PersonBox {
  Person person;
}

struct Node {
  union {
    int32 num;
    Cons cons;  // <--- this is a candidate for struct inlining.
  }
}

struct Cons {
  Node fst;
  Node snd;
}
