// Copyright (c) 2015, the Dartino project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE.md file.

service PerformanceService {
  int32 echo(int32 n);

  int32 countTreeNodes(TreeNode* node);
  TreeNode* buildTree(int32 n);
}

struct TreeNode {
  List<TreeNode> children;
}
