#!/bin/bash
# Copyright (c) 2015, the Fletch project authors. Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE.md file.

set -e

BUILD_DIR=$(pwd)/out/DebugIA32Clang
FLETCH_AGENT_SNAPSHOT=${BUILD_DIR}/fletch-agent.snapshot
export FLETCH_VM=${BUILD_DIR}/fletch-vm
export AGENT_IP=127.0.0.1
export AGENT_PORT=12121
export AGENT_PID_FILE=${BUILD_DIR}/agent/var/run/fletch-agent.pid
export AGENT_LOG_FILE=${BUILD_DIR}/agent/var/log/fletch-agent.log
export VM_LOG_DIR=${BUILD_DIR}/agent/var/log/fletch
export VM_PID_DIR=${BUILD_DIR}/agent/var/run/fletch

# Create required files.
mkdir -p ${VM_LOG_DIR} ${VM_PID_DIR}
touch ${AGENT_PID_FILE} ${AGENT_LOG_FILE}

# Create snapshot
${BUILD_DIR}/dart -c -Dsnapshot=${FLETCH_AGENT_SNAPSHOT} \
    tests/fletchc/run.dart pkg/fletch_agent/bin/agent.dart

# Run the agent
exec ${FLETCH_VM} ${FLETCH_AGENT_SNAPSHOT}
