// Copyright (c) 2015, the Fletch project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

service Foo {
  // Multiple formals should all have primitive types.
  void bar(int32 baz, Bar zap);
}

struct Bar {
}
