// Copyright (c) 2015, the Fletch project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

service Foo {
  // Invalid: The arguments should be either all primitive or a single one of
  // pointer type.
  Baz* bar(Baz* baz1, Baz* baz2);
}

struct Baz {
  List<Baz> keks;
}
