// Copyright (c) 2015, the Dartino project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

service Foo {
  // There is no limit on the number of arguments.
  void bar(int32  baz1, int32  baz2, int32  baz3, int32  baz4, int32  baz5,
           int32  baz6, int32  baz7, int32  baz8, int32  baz9, int32 baz10,
           int32 baz11, int32 baz12, int32 baz13, int32 baz14, int32 baz15,
           int32 baz16, int32 baz17, int32 baz18, int32 baz19, int32 baz20,
           int32 baz21, int32 baz22, int32 baz23, int32 baz24, int32 baz25,
           int32 baz26, int32 baz27, int32 baz28, int32 baz29, int32 baz30,
           int32 baz31, int32 baz32);
}
