// Copyright (c) 2015, the Fletch project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// bad service
service Painter {
  void draw(Circle c)  // bad function, expected pointer or primitive

struct Circle {
  int radius;  // bad simple type
  Point2d position position;  // bad member
}

struct Point2d {
  int x;  // bad simple type
  int y;  // bad simple type
}
